name = "AlphaVantage"
uuid = "7c748b61-afef-4b4f-aa5a-91235e183bae"
authors = ["Matthew-Amos <MatthewAmos@live.com>"]
version = "0.1.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
