module AlphaVantage

const HTTP_SCHEME = "https"
const HTTP_HOST = "alphavantage.co/query"
const ENV_VARIABLE_API_KEY = "ALPHA_VANTAGE_API_KEY"
const DEFAULT_API_KEY = "demo"

using HTTP
using CSV
using DataFrame
using ArgCheck

include("av_types.jl")
include("av_http.jl")
include("av_handlers.jl")

export
  AlphaVantageClient

export
  AVFunction,
    AVTimeSeries,
      TIME_SERIES_INTRADAY,
      TIME_SERIES_INTRADAY_EXTENDED,
      TIME_SERIES_DAILY,
      TIME_SERIES_DAILY_ADJUSTED,
      TIME_SERIES_WEEKLY,
      TIME_SERIES_WEEKLY_ADJUSTED,
      TIME_SERIES_MONTHLY,
      TIME_SERIES_MONTHLY_ADJUSTED,
      GLOBAL_QUOTE,
      SYMBOL_SEARCH,
    AVFundamental,
      INCOME_STATEMENT,
      BALANCE_SHEET,
      CASH_FLOW,
      EARNINGS,
      OVERVIEW,
      LISTING_STATUS,
      EARNINGS_CALENDAR,
      IPO_CALENDAR,
    AVCurrency,
      CURRENCY_EXCHANGE_RATE,
      FX_INTRADAY,
      FX_DAILY,
      FX_WEEKLY,
      FX_MONTHLY,
      AVC_PRICE,
      CRPYTO_INTRADAY,
      DIGITAL_CURRENCY_DAILY,
      DIGITAL_CURRENCY_WEEKLY,
      DIGITAL_CURRENCY_MONTHLY,
    AVEconomicIndicator,
      REAL_GDP,
      REAL_GDP_PER_CAPITA,
      TREASURY_YIELD,
      FEDERAL_FUNDS_RATE,
      INFLATION,
      INFLATION_EXPECTATION,
      CONSUMER_SENTIMENT,
      RETAIL_SALES,
      DURABLES,
      UNEMPLOYMENT,
      NONFARM_PAYROLL,
    AVTechnicalIndicator,
      SMA,
      EMA,
      WMA,
      DEMA,
      TEMA,
      TRIMA,
      KAMA,
      MAMA,
      VWAP,
      T3,
      MACD,
      MACDEXT,
      STOCH,
      STOCHF,
      RSI,
      STOCHRSI,
      WILLR,
      ADX,
      ADXR,
      APO,
      PPO,
      MOM,
      BOP,
      CCI,
      CMO,
      ROC,
      ROCR,
      AROON,
      AROONOSC,
      MFI,
      TRIX,
      ULTOSC,
      DX,
      MINUS_DI,
      PLUS_DI,
      MINUS_DM,
      PLUS_DM,
      BBANDS,
      MIDPOINT,
      MIDPRICE,
      SAR,
      TRANGE,
      ATR,
      NATR,
      AD,
      ADOSC,
      OBV,
      HT_TRENDLINE,
      HT_SINE,
      HT_TRENDMODE,
      HT_DCPERIOD,
      HT_DCPHASE,
      HT_PHASOR

end # module
